environment: development

apphost: k8s

label:
  name: sample-react-app

container:
  name: sample-react-app
  pullPolicy: IfNotPresent
  image: bhavik0907/react-helm
  tag: latest
  port: 80

replicas: 3

service:
  port: 8080
  type: NodePort
configValues: |
  window.REACT_APP_AXCO_IQ_API_ENDPOINT='https://www.bookmarks.dev/api/public/bookmarks'  
