apiVersion: v1
kind: Secret
metadata:
 name: registrypullsecret
data:
 .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnt9fSwiY3JlZHNTdG9yZSI6ImRlc2t0b3AiLCJleHBlcmltZW50YWwiOiJlbmFibGVkIiwic3RhY2tPcmNoZXN0cmF0b3IiOiJzd2FybSJ9
type: kubernetes.io/dockerconfigjson
