apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: {{ .Values.container.port }}
      nodePort: 31517
  selector:
    app: {{ .Values.label.name }}

